start C98.bat
start AAVE.bat
start ADA.bat
start AXS.bat
start ATOM.bat
start AVAX.bat
start CAKE.bat
start DAI.bat
start DOT.bat
start DOGE.bat
start EGLD.bat
start EOS.bat
start FIL.bat
start LDO.bat
start LINK.bat
start LTC.bat
start LUNC.bat
start MATIC.bat

start MKR.bat
start NEAR.bat
start OP.bat
start TON.bat
start TRX.bat
start TUSD.bat
start UNI.bat
start USDC.bat
start USDD.bat
start XRP.bat
